#!/bin/bash

FNAME=$(date +%y_%m_%d)

GLOBIGNORE="*"

FILETYPES="*.cpp *.h Makefile.in Makefile mergelib"

echo Creating backup file prg$FNAME.rar with following files $FILETYPES

#rar a -r -rr -s prg$FNAME.rar '*.cpp' '*.h' Makefile.in Makefile
rar a -r -rr -s prg$FNAME.rar $FILETYPES -x\EXAM/*

echo Backup file prg$FNAME.rar was created
