#ifndef GENFILE_H
#define GENFILE_H

#include "basefun.h"
#include "cr.h"
#include "densemat.h"
#include "difcalc.h"
#include "dskyline.h"
#include "eigsol.h"
#include "elemmat.h"
#include "elemtools.h"
#include "fuzzygen.h"
#include "fuzzynum.h"
#include "gadaptivity.h"
#include "gelement.h"
#include "gfunct.h"
#include "gmatrix.h"
#include "gnode.h"
#include "gtopology.h"
#include "intools.h"
#include "intp.h"
#include "iotools.h"
#include "kwdset.h"
#include "lgnode.h"
#include "mathem.h"
#include "matrix.h"
#include "ordering.h"
#include "saddpoint.h"
#include "scr.h"
#include "skyline.h"
#include "slesolv.h"
#include "tablefunct.h"
#include "tensor.h"
#include "timecontr.h"
#include "vector.h"
#include "xfile.h"

#include "PARSER/parser.h"
#include "PARSER/equ.h"

//#include "CMLFILE/cmlfile.h"

#endif
